export const shoedata = [
  {
    id: 1,
    name: "Off-White",
    desc: 'Out Of Office "Ooo" sneakers',
    price: 775,
    link: "prd1",
    imgdeskmain: "/Images/Shoe11.png",
    imgmobmain: "/Images/Shoe11.png",
    alt: "Nike Air Max 270",
    imgdesk: ["/Images/Shoe11.png", "/Images/Shoe12.png", "/Images/Shoe13.png"],
    imgmob: [
      "/Images/Shoe11.png",
      "/Images/Shoe12small.png",
      "/Images/Shoe13small.png",
    ],
    imgdesc: "/Images/Shoe14.png",
    ship: 10,
    tax: 3,
    discount: 3,
  },
  {
    id: 2,
    name: "Nike",
    price: 200,
    desc: "Nike Gamma Force",
    link: "prd2",
    imgdeskmain: "/Images/Shoe21.png",
    imgmobmain: "/Images/Shoe21small.png",
    alt: "Nike Air Max 270",
    imgdesk: ["/Images/Shoe21.png", "/Images/Shoe22.png", "/Images/Shoe23.png"],
    imgmob: [
      "/Images/Shoe21small.png",
      "/Images/Shoe22small.png",
      "/Images/Shoe23small.png",
    ],
    imgdesc: "/Images/Shoe24.png",
    ship: 10,
    tax: 3,
    discount: 3,
  },
  {
    id: 3,
    name: "Nike",
    price: 160,
    desc: "Cosmic Unity 3",
    link: "prd3",
    imgdeskmain: "/Images/Shoe31.png",
    imgmobmain: "/Images/Shoe31small.png",
    alt: "Nike Air Max 270",
    imgdesk: ["/Images/Shoe31.png", "/Images/Shoe32.png", "/Images/Shoe33.png"],
    imgmob: [
      "/Images/Shoe31small.png",
      "/Images/Shoe32small.png",
      "/Images/Shoe33small.png",
    ],
    imgdesc: "/Images/Shoe34.png",
    ship: 10,
    tax: 3,
    discount: 3,
  },
  {
    id: 4,
    name: "Adidas",
    price: 160,
    desc: "DAILY 3.0 SHOES",
    link: "prd4",
    imgdeskmain: "/Images/Shoe41.png",
    imgmobmain: "/Images/Shoe41small.png",
    alt: "Nike Air Max 270",
    imgdesk: ["/Images/Shoe41.png", "/Images/Shoe42.png", "/Images/Shoe43.png"],
    imgmob: [
      "/Images/Shoe41small.png",
      "/Images/Shoe42small.png",
      "/Images/Shoe43small.png",
    ],
    imgdesc: "/Images/Shoe44.png",
    ship: 10,
    tax: 3,
    discount: 3,
  },
];
